notifications:
  webhooks:
    - https://webhook.commit-email.info/

dist: xenial

services:
  - docker

redmine_4_0: &redmine_4_0
  install:
    - bundle install
    - bin/rails db:create
    - bin/rails generate_secret_token
    - bin/rails db:migrate
    - bin/rails redmine:load_default_data REDMINE_LANG=en
    - bin/rails redmine:plugins:migrate
    - bin/rails db:structure:dump
  script:
    - RAILS_ENV=test bin/rails redmine:plugins:test
    - bin/rails redmine:plugins:migrate NAME=full_text_search VERSION=0
    - bin/rails redmine:plugins:migrate NAME=full_text_search

matrix:
  include:
    - name: "Redmine 4.0 & MySQL"
      <<: *redmine_4_0
      env:
        - REDMINE_VERSION=4.0
        - RDBMS=mysql
        - RDBMS_PORT=3306
        - GROONGA_ADAPTER=mroonga
    - name: "Redmine 4.0 & PostgreSQL"
      <<: *redmine_4_0
      env:
        - REDMINE_VERSION=4.0
        - RDBMS=postgresql
        - RDBMS_PORT=5432
        - GROONGA_ADAPTER=pgroonga
        - DOCKER_TAG="latest-debian-11"
      addons:
        apt:
          packages:
            - postgresql-client-11

before_install:
  - docker run
      --detach
      -p ${RDBMS_PORT}:${RDBMS_PORT}
       groonga/${GROONGA_ADAPTER}:${DOCKER_TAG:-latest}
  - cd ..
  - git clone
      --depth 1
      --branch ${REDMINE_VERSION}-stable
      https://github.com/redmine/redmine.git
  - cd redmine
  - svnadmin create tmp/test/subversion_repository
  - zcat test/fixtures/repositories/subversion_repository.dump.gz |
      svnadmin load tmp/test/subversion_repository
  - tar xf test/fixtures/repositories/git_repository.tar.gz -C tmp/test
  - cd plugins
  - ln -s ../../redmine_full_text_search ./full_text_search
  - cd ../
  - cp plugins/full_text_search/config/database.yml.example.${REDMINE_VERSION}.${RDBMS}
      config/database.yml
  - cp plugins/full_text_search/config/initializers/schema_format.rb
      config/initializers/schema_format.rb
  - unset BUNDLE_GEMFILE
